### ISSUE TITLE
Get App ID

### ISSUE THREAD

**Issue by clubmagic87** [giangvo/synology-fshare#1]
Bác có thể hướng dẫn cách lấy App ID không.
$this->AppId = "GUxft6Beh3Bf8qKP7GC2IplYJZz1A53JQfRwne0R";

**Comment by giangvo** [comment]
Hinh nhu appId ko quan trong dau. Ban thu set dai 1 random string coi sao. (Lau wa roi minh cug ko con nho :) )

**Comment by clubmagic87** [comment]
Trước có ngươì bảo lấy cái mã này trong Fshare app (ios or apk), phải debug ra.
Chứ hiện tại code này không còn hoạt động nữa :(

**Comment by giangvo** [comment]
Minh vua check, no van work ma. Minh ko nho la phai lay tu fshare app

**Comment by giangvo** [comment]
```
curl -H "Content-type: application/json" -XPOST -d '{"password":"pass", "user_email":"email", "app_key":"GUxft6Beh3Bf8qKP7GC2IplYJZz1A53JQfRwne0R"}' https://api2.fshare.vn/api/user/login
```
output:
```
{"code":200,"msg":"Login successfully!","token":"token123","session_id":"sesssionid13"}
```

**Comment by clubmagic87** [comment]
À nó báo failed khi download file.
Array
(
    [DOWNLOAD_ERROR] => Login fail!
)
Đó, nó báo thế nên mình tưởng key không sử dụng được nữa.

**Comment by clubmagic87** [comment]
Siệt =))
Curl tay thì ra link, còn code kia thì báo failed login :v

**Comment by clubmagic87** [comment]
Mình tìm ra vấn đề rồi.
Do cái lỗi này "SSL certificate : unable to get local issuer certificate"
Mình đã fix nó xong :D
Thanks bác đã support nhé
